### ISSUE TITLE
 go struct turn back to sql

### ISSUE THREAD

**Issue by alfredo-linux** [pganalyze/pg_query_go#23] opened 2019-08-14 08:45 UTC
I parse my pgsql to go struct, and I have changed some value of the  struct's members,  How can i make the struct turn back to pgsqls?

**Comment by tpoxa** [comment] 2020-02-14 10:43
@alfredo-linux  Hi. Did you find solution?

**Comment by ehfeng** [comment] 2020-05-05 07:47
Duplicate of https://github.com/lfittl/pg_query_go/issues/4, where the author discusses approaches.

**Comment by lfittl** [comment] 2021-03-18 22:14
This has been implemented now, see this example in the readme: https://github.com/pganalyze/pg_query_go#deparsing-a-parse-tree-back-into-a-sql-statement-experimental

**Closed by lfittl** 2021-03-18 22:14 UTC
