### ISSUE TITLE
Has an issue with the parser package after update to MacOS 13

### ISSUE THREAD

**Issue by TruongNguyenLava** [pganalyze/pg_query_go#66] opened 2022-11-03 10:31 UTC
_System:_
Machine: `Macbook Pro M1`
Go version: `1.19.3`
OS: `MacOS 13`
pg_query_go: `1.0.3`

_Summary_
I don't understand why there is an error from XCode, maybe this error is related to MacOS 13.
I have googled to try to solve this but no success, do you have any ideas?

![image](https://user-images.githubusercontent.com/97141477/199696788-92554eba-0bd3-4737-a976-155910b88baa.png)

**Comment by ulfmagnetics** [comment] 2022-11-03 18:47
The underlying issue appears to be a conflict between clang v14.0.0 and the sqlc module -- see [this issue](https://github.com/kyleconroy/sqlc/issues/1889#issuecomment-1302528723). I was able to work around it by installing the Command Line Tools for XCode 13.4 from [here](https://developer.apple.com/download/all/?q=for%20Xcode), though I'm still on Monterey and I'm not sure if this will still work for Ventura.

**Comment by TruongNguyenLava** [comment] 2022-11-04 01:10
Thank you @ulfmagnetics, but I can't install `Command Line Tools for XCode 13.4` on MacOS 13.

![image](https://user-images.githubusercontent.com/97141477/199863473-8bfa9bac-0556-49cf-8403-c791622944e8.png)

**Comment by lfittl** [comment] 2022-11-04 02:47
@TruongNguyenLava This might be the same issue that was fixed in version 2.2.0 (see https://github.com/pganalyze/pg_query_go/pull/64 and https://github.com/pganalyze/libpg_query/pull/156)

Are you seeing this with sqlc, or something else? (I've opened up a PR on sqlc to get the library dependency updated: https://github.com/kyleconroy/sqlc/pull/1921)

**Comment by TruongNguyenLava** [comment] 2022-11-05 07:55
Thanks @lfittl everything works perfectly in 2.2.0

**Closed** 2022-11-05 07:56 UTC

**Comment by funny-falcon** [comment] 2022-11-08 07:39
The problem is in bison: native MacOS bison is very old (2.2). It defines a lot of garbage macroses before include directives.

Instalation of bison 3.8.2 with brew fixed compilation.
